### PR TITLE
android: implement field errors for login screen

### LINKED ISSUE #186: Android: Expose Backend Error Messages in Login
For registration, getting the error code from the response is better. If you don't want to throw or catch exception, I suggest creating a Response object outside of the call and pass it in (kinda like what we do with pointer in C)

_Originally posted by @TanoVip123 in https://github.com/ParkWithEase/parkeasy/pull/111#discussion_r1791131602_

### PR DESCRIPTION
**Pull request by ioreel**
Refactored login screen layout:

- Less hard-coded numbers by describing how contents should be laid out
- Allow screen to scroll and adapt when on-screen keyboard is open, previously the keyboard would obstruct fields and buttons when open, preventing users from interacting with them.
- Dropped various state and event classes. Instead raise the function parameter limits to handle the massive amount of callbacks.
- Added preview functions to allow for easier testing and experimenting without running the emulator.

Refactored user repository:

- Operations reachable from LoginViewModel now returns `Result<Unit>`, capturing exceptions (if any), forcing consumers to react to them. The ability to define extensions over `Result<T>` is also helpful for allowing code reuse.
- Now correctly handles cookie invalidation requests from the backend.

New features:

- Errors from the backend are now parsed and used to annotate fields with error states.
- Handles network errors and notify users about the issue instead of crashing.

Known issues:

- Heavy coupling between LoginViewModel and remote server specifics (ie. ErrorModel, IOException).
- Some class locations should probably be moved (ie. Login*State, APIException).

Fixes #186

---

This was done as an exercise to see if the new error model on the backend works. So far I'd say that it's fairly OK to use.

I've not extensively tested the new screen, so some double-checking would be appreciated.

Here are some UI screenshots:

<details>

<summary>IME scrolling the view</summary>

image

</details>

<details>

<summary>Field errors</summary>

image

image

</details>

### CODE REVIEW

File: android/app/src/main/java/io/github/parkwithease/parkeasy/ui/login/LoginViewModel.kt [hunk 1]
```diff
@@ -30,40 +37,144 @@ constructor(
...
-                if (result) "Reset email sent\nJk... we're working on it"
-                else "Error resetting password",
-                null,
-            )
+            _formEnabled.value = false
+            userRepo
+                .requestReset(ResetCredentials(formState.email.value))
+                .onSuccess { showSnackbar("Reset email sent\nJk... we're working on it", null) }
+                .recoverRequestErrors("Error resetting password")
+            _formEnabled.value = true
```
Comment (edwinduong) [inline android/app/src/main/java/io/github/parkwithease/parkeasy/ui/login/LoginViewModel.kt:83]: The login form is disabled for the duration of the snackbar being shown instead of the API request, this is most noticeable on the forgot password screen

Comment (edwinduong) [reply android/app/src/main/java/io/github/parkwithease/parkeasy/ui/login/LoginViewModel.kt:83]: image
image

File: android/app/src/main/java/io/github/parkwithease/parkeasy/ui/login/LoginViewModel.kt [hunk 2]
```diff
@@ -30,40 +37,144 @@ constructor(
...
+            when (err.location) {
+                "body.email" ->
+                    formState =
+                        formState.run { copy(email = email.copy(error = "Invalid email address")) }
+
+                "body.password" ->
+                    formState =
+                        formState.run { copy(password = password.copy(error = "Invalid password")) }
+            }
         }
```
Comment (edwinduong) [inline android/app/src/main/java/io/github/parkwithease/parkeasy/ui/login/LoginViewModel.kt:169]: Errors don't properly get cleared which leads to misleading error messages

Comment (edwinduong) [reply android/app/src/main/java/io/github/parkwithease/parkeasy/ui/login/LoginViewModel.kt:169]: Having a password error makes the email error persist
image
image

**Review by edwinduong — CHANGES_REQUESTED** [review]
Just some UI/UX things but everything else looks good

**Review by edwinduong — APPROVED** [review]
